### ISSUE TITLE
Split the script into two distinct Actions

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os/deno-deploy#5]
It would be nice to split the deploy into two different scripts, which would make more sense in terms on reusability for other projects.

Example:
<details>

<summary>new deno deploy template</summary>

https://github.com/0x4007/pi-vpn/blob/main/.github/actions/deno-deploy/action.yml

```yaml
name: "Deno Deploy Reusable Template"
description: "Checks out the repository and publishes or deletes the project on Deno Deploy. The project name must be provided by the workflow."
inputs:
  action:
    description: "Action to perform: 'deploy' or 'delete' the project."
    required: true
    default: "deploy"
  token:
    description: "Deno Deploy access token."
    required: true
  entrypoint:
    description: "The entrypoint to the script that will be deployed."
    required: false
    default: "worker/main.ts"
  root:
    description: "The root directory of the script that will be deployed."
    required: false
    default: "."
  project_name:
    description: "The Deno Deploy project name. Must be provided by the workflow."
    required: true
  organization:
    description: "The organization to target when deploying the project. If omitted, will default to the user account."
    required: false
  env_file:
    description: "Path to .env file to use during deployment"
    required: false
    default: ""
  production:
    description: "Deploy to production (uses --prod flag)"
    required: false
    default: "true"
outputs:
  deployment_url:
    description: "The deployment URL"
    value: ${{ steps.get_deployment_url.outputs.url }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Install deployctl
      shell: bash
      run: |
        set -euo pipefail
        deno install --global --allow-read --allow-write --allow-env --allow-net --allow-run --allow-sys --no-check -r -f https://deno.land/x/deploy@1.12.0/deployctl.ts
        echo "DENO_PROJECT_NAME=${{ inputs.project_name }}" >> $GITHUB_ENV

        # Verify installation
        if ! command -v deployctl &> /dev/null; then
          echo "❌ ERROR: deployctl installation failed"
          exit 1
        fi
        echo "✅ deployctl installed successfully"

    - name: Manage Deno Deploy Project (Deploy)
      if: inputs.action == 'deploy'
      shell: bash
      env:
        DENO_DEPLOY_TOKEN: ${{ inputs.token }}
        DENO_PROJECT_NAME: ${{ inputs.project_name }}
      run: |
        set -euo pipefail
        echo "Deploying project: $DENO_PROJECT_NAME"

        # Validate entrypoint exists
        if [ ! -f "${{ inputs.root }}/${{ inputs.entrypoint }}" ]; then
          echo "❌ ERROR: Entrypoint file not found: ${{ inputs.root }}/${{ inputs.entrypoint }}"
          exit 1
        fi

        # Function to try creating project
        create_project() {
          local org_flag="$1"
          deployctl projects create \
            --token=$DENO_DEPLOY_TOKEN \
            --project=$DENO_PROJECT_NAME \
            $org_flag \
            --color=never 2>&1
        }

        # Function to check if project exists
        project_exists() {
          deployctl projects show \
            --token=$DENO_DEPLOY_TOKEN \
            --project=$DENO_PROJECT_NAME \
            --color=never > /dev/null 2>&1
        }

        # Check if project already exists
        if project_exists; then
          echo "Project already exists, skipping creation"
        elif [ -n "${{ inputs.organization }}" ]; then
          echo "Attempting to create project in organization: ${{ inputs.organization }}"

          # Try to create with organization
          output=$(create_project "--org=${{ inputs.organization }}")
          exit_code=$?

          if [ $exit_code -ne 0 ]; then
            echo "$output"

            # Check if error is due to missing organization
            if echo "$output" | grep -q -E "(organization|org|team) .* (not found|does not exist|doesn't exist)"; then
              echo ""
              echo "⚠️  WARNING: Organization '${{ inputs.organization }}' not found in Deno Deploy"
              echo ""
              echo "Attempting to create project under personal account instead..."

              # Try without organization (personal account)
              if ! create_project ""; then
                echo ""
                echo "❌ ERROR: Failed to create project in both organization and personal account"
                echo ""
                echo "To fix this issue, you have two options:"
                echo ""
                echo "1. Create a Deno Deploy organization/team named '${{ inputs.organization }}' at:"
                echo "   https://dash.deno.com/account#organizations"
                echo ""
                echo "2. Remove the organization parameter from your workflow to deploy to your personal account"
                echo ""
                echo "For more information, see: https://docs.deno.com/deploy/manual/organizations"
                exit 1
              fi

              echo "✅ Successfully created project under personal account"
              echo ""
              echo "ℹ️  Note: To deploy to an organization in the future, create a team named"
              echo "   '${{ inputs.organization }}' at https://dash.deno.com/account#organizations"
            else
              # Other error, exit
              echo "❌ ERROR: Failed to create project"
              exit 1
            fi
          else
            echo "✅ Successfully created project in organization: ${{ inputs.organization }}"
          fi
        else
          # No organization specified, create in personal account
          echo "Creating project in personal account (no organization specified)"
          if ! create_project ""; then
            echo "❌ ERROR: Failed to create project"
            exit 1
          fi
          echo "✅ Successfully created project"
        fi

        # Build deployment command
        DEPLOY_CMD="deployctl deploy \
          --token=$DENO_DEPLOY_TOKEN \
          --project=$DENO_PROJECT_NAME \
          --entrypoint=${{ inputs.entrypoint }} \
          --root=${{ inputs.root }} \
          --color=never"

        # Add production flag if enabled
        if [ "${{ inputs.production }}" = "true" ]; then
          DEPLOY_CMD="$DEPLOY_CMD --prod"
        fi

        # Add env file if provided
        if [ -n "${{ inputs.env_file }}" ] && [ -f "${{ inputs.env_file }}" ]; then
          DEPLOY_CMD="$DEPLOY_CMD --env-file=${{ inputs.env_file }}"
        fi

        # Execute deployment
        echo ""
        echo "Executing deployment..."
        eval $DEPLOY_CMD

    - name: Get Deployment URL
      if: inputs.action == 'deploy'
      id: get_deployment_url
      shell: bash
      env:
        DENO_DEPLOY_TOKEN: ${{ inputs.token }}
        DENO_PROJECT_NAME: ${{ inputs.project_name }}
      run: |
        set -euo pipefail

        # Get the deployment URL from Deno
        echo "Fetching deployment URL..."
        PROJECT_INFO=$(deployctl projects show --token=$DENO_DEPLOY_TOKEN --project=$DENO_PROJECT_NAME --color=never || true)

        # Try multiple patterns to extract URL
        PROJECT_URL=""
        if [ -n "$PROJECT_INFO" ]; then
          # Try to extract from Domain(s): line
          PROJECT_URL=$(echo "$PROJECT_INFO" | grep -i "domain" | sed -E 's/.*Domain\(s\):[[:space:]]+([^[:space:]]+).*/\1/' || true)

          # If not found, try to find any .deno.dev URL
          if [ -z "$PROJECT_URL" ]; then
            PROJECT_URL=$(echo "$PROJECT_INFO" | grep -o "[a-zA-Z0-9-]*\.deno\.dev" | head -n1 || true)
          fi
        fi

        # Fallback to constructed URL if extraction failed
        if [ -z "$PROJECT_URL" ]; then
          PROJECT_URL="https://${DENO_PROJECT_NAME}.deno.dev"
          echo "⚠️  WARNING: Could not extract URL from deployctl output, using constructed URL: $PROJECT_URL"
        fi

        echo "url=$PROJECT_URL" >> $GITHUB_OUTPUT
        echo "Deployment URL: $PROJECT_URL"

        # Write to step summary
        echo "### 🚀 Deployment Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Project:** $DENO_PROJECT_NAME" >> $GITHUB_STEP_SUMMARY
        echo "**URL:** $PROJECT_URL" >> $GITHUB_STEP_SUMMARY
        if [ "${{ inputs.production }}" = "true" ]; then
          echo "**Environment:** Production" >> $GITHUB_STEP_SUMMARY
        else
          echo "**Environment:** Preview" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Manage Deno Deploy Project (Delete)
      if: inputs.action == 'delete'
      shell: bash
      env:
        DENO_DEPLOY_TOKEN: ${{ inputs.token }}
        DENO_PROJECT_NAME: ${{ inputs.project_name }}
      run: |
        set -euo pipefail
        echo "Deleting project: $DENO_PROJECT_NAME"

        # Attempt to delete the project
        if deployctl projects delete \
          --token=$DENO_DEPLOY_TOKEN \
          --project=$DENO_PROJECT_NAME \
          --force \
          --color=never; then
          echo "✅ Successfully deleted project: $DENO_PROJECT_NAME"

          # Write to step summary
          echo "### 🗑️ Project Deleted" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Project:** $DENO_PROJECT_NAME" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** Successfully deleted" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ ERROR: Failed to delete project: $DENO_PROJECT_NAME"

          # Write error to step summary
          echo "### ❌ Deletion Failed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Project:** $DENO_PROJECT_NAME" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** Failed to delete" >> $GITHUB_STEP_SUMMARY

          exit 1
        fi
```
</details>

<details>
<summary>new plugin adapter template</summary>

https://github.com/0x4007/pi-vpn/blob/main/.github/actions/plugin-adapter/action.yml

```yaml
name: "Deno Deploy Plugin Adapter"
description: "Converts a plugin into a Deno-compatible deployment by creating entry points and handling manifest updates."
inputs:
  pluginEntry:
    description: "The path to the plugin entry file. It is expected to export 'fetch' as a default."
    required: false
    default: "./worker"
outputs:
  project_name:
    description: "The generated Deno project name"
    value: ${{ steps.prepare_env.outputs.project_name }}
  deployment_url:
    description: "The deployment URL (only available after deployment)"
    value: ${{ steps.prepare_env.outputs.deployment_url }}
  entrypoint:
    description: "The generated Deno entry point path"
    value: "src/deno.ts"
  manifest_exists:
    description: "Whether manifest.json exists in the repository"
    value: ${{ steps.check_manifest.outputs.exists }}
  env_file_path:
    description: "Path to the temporary .env file (in CI temp directory)"
    value: ${{ steps.generate_env.outputs.env_file_path }}
runs:
  using: "composite"
  steps:
    - name: Prepare Environment Variables
      id: prepare_env
      shell: bash
      run: |
        set -euo pipefail

        # Extract branch name and sanitize it
        branch_name=$(echo '${{ github.event.ref || github.event.workflow_run.head_branch || github.ref }}' | sed 's#refs/heads/##')

        # Create a more unique sanitization to avoid collisions
        # Replace slashes with double dashes to distinguish from regular dashes
        sanitized_branch=$(echo "$branch_name" | sed 's#/#--#g' | sed 's#[^a-zA-Z0-9-]#-#g')

        project_name="${{ github.event.repository.name }}"
        new_name="${project_name}-${sanitized_branch}"

        # Deno project names cannot exceed 26 characters
        # If too long, use hash of the branch name to ensure uniqueness
        if [ ${#new_name} -gt 26 ]; then
          # Get first 10 chars of project name and 8 chars of branch hash
          project_prefix=$(echo "$project_name" | cut -c 1-10)
          branch_hash=$(echo "$branch_name" | sha256sum | cut -c 1-8)
          new_name="${project_prefix}-${branch_hash}"
        fi

        echo "DENO_PROJECT_NAME=$new_name" >> $GITHUB_ENV
        echo "project_name=$new_name" >> $GITHUB_OUTPUT
        DENO_DEPLOYMENT_ID=${{ github.sha }}
        echo "DENO_DEPLOYMENT_ID=$DENO_DEPLOYMENT_ID" >> $GITHUB_ENV

        echo "Generated project name: $new_name"

    - name: Generate .env File in Temp Directory
      id: generate_env
      shell: bash
      run: |
        # Create a temporary directory for the .env file
        TEMP_ENV_DIR="${RUNNER_TEMP}/deno-deploy-env"
        mkdir -p "$TEMP_ENV_DIR"
        ENV_FILE_PATH="$TEMP_ENV_DIR/.env"

        cat > generate-env.ts <<'EOF'
        const envVars = Deno.env.toObject();
        const filtered = Object.entries(envVars)
          .filter(([k, v]) => !/^(GITHUB_|RUNNER_|CI|HOME|PATH|PWD|SHELL|USER|LANG|LC_|TZ|ACTIONS_)/.test(k))
          .filter(([k, v]) => v !== undefined && v !== null && v.trim() !== "")
          .reduce((acc, [k,v]) => ({...acc, [k]:v}), {});

        const envPath = Deno.args[0];
        await Deno.writeTextFile(envPath,
          Object.entries(filtered)
            .map(([k,v]) => `${k}="${v.replace(/"/g, '\\"')}"`)
            .join("\n")
        );
        EOF

        deno run --allow-env --allow-write="$TEMP_ENV_DIR" generate-env.ts "$ENV_FILE_PATH"
        rm generate-env.ts

        echo "env_file_path=$ENV_FILE_PATH" >> $GITHUB_OUTPUT
        echo "Generated .env file at: $ENV_FILE_PATH"

    - name: Create Deno Entry Point
      shell: bash
      run: |
        mkdir -p src
        cat << 'EOF' > src/deno.ts
        import worker from "${{ inputs.pluginEntry }}";
        export default {
          async fetch(request: Request, env: Record<string, unknown>, executionCtx?: ExecutionContext) {
            Object.assign(env, Deno.env.toObject());
            return worker.fetch(request, env, executionCtx);
          },
        };
        EOF

    - name: Fix Import Extensions
      shell: bash
      run: |
        find src -name "*.ts" -type f -exec sh -c '
          sed -i.bak "
            s/from \"\(\.\+[^\"]*\)\.json\"/from \"\1.json\" with { type: \"json\" }/g;
            s/from '"'"'\(\.\+[^'"'"']*\)\.json'"'"'/from '"'"'\1.json'"'"' with { type: \"json\" }/g;
            s/from \"\(\.\+[^\"]*\)\"/from \"\1.ts\"/g;
            s/from '"'"'\(\.\+[^'"'"']*\)'"'"'/from '"'"'\1.ts'"'"'/g;
            s/\.json\.ts\" with { type: \"json\" }/.json\" with { type: \"json\" }/g;
            s/\.css\.ts/.css/g;
            s/\.svg\.ts/.svg/g;
            s/\.ts\.ts/.ts/g
          " "$1"
        ' _ {} \;
        find src -name "*.ts.bak" -delete

    - name: Check if manifest.json exists
      id: check_manifest
      shell: bash
      run: |
        if [ -f manifest.json ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Update manifest.json with deployment URL
      if: steps.check_manifest.outputs.exists == 'true'
      shell: bash
      run: |
        set -euo pipefail

        # Construct the deployment URL
        DEPLOYMENT_URL="https://${{ steps.prepare_env.outputs.project_name }}.deno.dev"
        echo "Updating manifest.json with deployment URL: $DEPLOYMENT_URL"

        # Create a Node.js script to update the manifest
        cat > update-manifest.js <<'EOF'
        const fs = require('fs');
        const path = require('path');

        const manifestPath = path.resolve(process.cwd(), './manifest.json');
        const deploymentUrl = process.argv[2];

        if (!fs.existsSync(manifestPath)) {
          console.error('manifest.json not found');
          process.exit(1);
        }

        try {
          const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
          manifest["homepage_url"] = deploymentUrl;

          const updatedManifest = JSON.stringify(manifest, null, 2);
          fs.writeFileSync(manifestPath, updatedManifest);
          console.log('Successfully updated manifest.json');
          console.log('Updated content:', updatedManifest);
        } catch (error) {
          console.error('Error updating manifest.json:', error);
          process.exit(1);
        }
        EOF

        # Run the Node.js script
        node update-manifest.js "$DEPLOYMENT_URL"

        # Clean up
        rm update-manifest.js

        # Format the manifest.json file with deno fmt if available
        if command -v deno &> /dev/null; then
          deno fmt --ext=json manifest.json || true
        fi

    - name: Store deployment URL
      id: store_url
      shell: bash
      run: |
        # This will be updated by the workflow after deployment
        echo "deployment_url=" >> $GITHUB_OUTPUT
```
</details>

<details>
<summary>example of how to use both</summary>

https://github.com/0x4007/pi-vpn/blob/main/.github/workflows/example.yml

```yaml
name: Deploy Plugin to Deno

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - delete

env:
  # GitHub App credentials for manifest updates (optional)
  APP_ID: ${{ secrets.APP_ID }}
  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

jobs:
  deploy-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Determine if we're on the default branch for production deployments
      - name: Check if default branch
        id: check-branch
        shell: bash
        run: |
          # Get the default branch name from GitHub API
          DEFAULT_BRANCH=$(curl -s -H "Authorization: token ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}" | \
            jq -r '.default_branch')

          # Get current branch name
          CURRENT_BRANCH="${{ github.ref_name }}"

          # Check if we're on the default branch
          if [ "$CURRENT_BRANCH" = "$DEFAULT_BRANCH" ]; then
            echo "is_default_branch=true" >> $GITHUB_OUTPUT
            echo "On default branch ($DEFAULT_BRANCH), will deploy to production"
          else
            echo "is_default_branch=false" >> $GITHUB_OUTPUT
            echo "Not on default branch (current: $CURRENT_BRANCH, default: $DEFAULT_BRANCH), will deploy to preview"
          fi

      # Step 1: Prepare the plugin for Deno deployment
      - name: Adapt Plugin for Deno
        id: plugin-adapter
        uses: ./.github/actions/plugin-adapter
        with:
          pluginEntry: "./worker"  # Path to your plugin entry file

      # Step 2: Deploy to Deno using the adapted plugin
      - name: Deploy to Deno
        id: deno-deploy
        if: github.event.inputs.action != 'delete'
        uses: ./.github/actions/deno-deploy
        with:
          action: deploy
          token: ${{ secrets.DENO_DEPLOY_TOKEN }}
          project_name: ${{ steps.plugin-adapter.outputs.project_name }}
          entrypoint: ${{ steps.plugin-adapter.outputs.entrypoint }}
          root: "."
          organization: ${{ github.repository_owner }}  # Dynamically use GitHub organization
          env_file: ${{ steps.plugin-adapter.outputs.env_file_path }}  # Use temp env file path
          production: ${{ steps.check-branch.outputs.is_default_branch }}  # Only production on default branch

      # Step 3: Post-deployment tasks

      - name: Get GitHub App token
        if: github.event.inputs.action != 'delete' && env.APP_ID != '' && env.APP_PRIVATE_KEY != ''
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ env.APP_PRIVATE_KEY }}

      - name: Commit manifest changes
        if: github.event.inputs.action != 'delete' && steps.plugin-adapter.outputs.manifest_exists == 'true'
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token || env.GITHUB_TOKEN }}
        with:
          files: |
            manifest.json
          commit-message: "chore: [skip ci] update manifest.json url"
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Write Deployment URL to Summary
        if: github.event.inputs.action != 'delete'
        shell: bash
        run: |
          echo "### Deployment URL" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.deno-deploy.outputs.deployment_url }}" >> $GITHUB_STEP_SUMMARY

          if [ "${{ steps.check-branch.outputs.is_default_branch }}" = "true" ]; then
            echo "**Environment:** Production" >> $GITHUB_STEP_SUMMARY
          else
            echo "**Environment:** Preview" >> $GITHUB_STEP_SUMMARY
          fi

      # Delete action
      - name: Delete Deno Project
        if: github.event.inputs.action == 'delete'
        uses: ./.github/actions/deno-deploy
        with:
          action: delete
          token: ${{ secrets.DENO_DEPLOY_TOKEN }}
          project_name: ${{ steps.plugin-adapter.outputs.project_name }}

      - name: Write Deletion to Summary
        if: github.event.inputs.action == 'delete'
        shell: bash
        run: |
          echo "### Deployment URL" >> $GITHUB_STEP_SUMMARY
          echo "Deployment \`${{ steps.plugin-adapter.outputs.project_name }}\` has been deleted." >> $GITHUB_STEP_SUMMARY
```
</details>

Related recent commit: https://github.com/0x4007/pi-vpn/commit/9b5550594a5451227beb54e63a9131f3101b9d7d

RFC @0x4007
